// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-themes/ReadableDark.tsx": () => import("../components/mockups/login-themes/ReadableDark.tsx"),
  "./components/mockups/login-themes/SoftLight.tsx": () => import("../components/mockups/login-themes/SoftLight.tsx"),
  "./components/mockups/login-themes/WarmDark.tsx": () => import("../components/mockups/login-themes/WarmDark.tsx")
};
